### ISSUE TITLE
Wsparcie nowych kodów QR

### ISSUE THREAD

**Issue by domints** [TehFridge/Zappka3DS#1]
Cześć!

Wiesz już jak generowane są nowe kody QR? Ja w sumie wiem, chętnie się podzielę, ale chyba na priv, bo nie chciałbym, żeby przyszła zła żabka i zbanowała mi konto czy coś :D Mam działający kod w Pythonie (+ trzeba trochę popracować jeszcze z mitmproxy, bo nie rozpracowałem auth flow).

Czy ten projekt na 3DSa jest mi potrzebny? Absolutnie nie, ale jest tak kaktuśny, że chcę Ci pomóc :D

**Comment by TehFridge** [comment]
Mam już napisany renderer/encoder kodów QR ale nadal nie potrafię rozpracować jak encode'owane są te kody QR.
Tyle wiem że są skonstruowane w następujący sposób:
*url_do_dashboarda_żappki*/loyal=*6_cyfrowy_kod_TOTP*
Bardzo chętnie przyjmę pomoc!
Discord: tehfridge

**Comment by domints** [comment]
Szczerze mówiąc nie bardzo wiem jak mogę się do Ciebie dostać na Discordzie, to taki tech, którego niezupełnie ogarniam :D

Chyba wysłałem Ci zapro do znajomych? Chyba, że powinienem Cię szukać na jakimś serwerze?

**Comment by TehFridge** [comment]
Kody QR Support Added
https://github.com/TehFridge/Zappka3DS/releases/tag/v1.1.0
