### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by radeczekuwu** [TehFridge/Zappka3DS#2]
![IMG_3963](https://github.com/user-attachments/assets/e13daecb-da15-46b9-ba60-98db44ffadcb)
Hej, w wersji 1.2 oraz 1.21 cały czas wyrzuca mi taki błąd.

**Comment by TehFridge** [comment]
https://github.com/devkitPro/3ds-hbmenu/releases/tag/v2.4.3  Czy masz aktualną wersje Lumy i Homebrew Launchera?
Najnowsze wersje przychodzą z Certyfikatami SSL które pozwalają wgl na komunikacje z nowoczesnymi API itd.

**Comment by radeczekuwu** [comment]
Tak, mam najnowszą wersję 2.4.3. Updateowalem dziś specjalnie wszystko. Chyba że trzeba zrobić tym razem coś więcej niż zawsze się robiło. Update robiłem przez Universal Updater

**Comment by TehFridge** [comment]
![image](https://github.com/user-attachments/assets/85463e69-7818-455e-ae77-1f4825866b87) Weź może sprawdź czy masz taki plik w tym katalogu. (ścieżka na obrazku lol)

**Comment by radeczekuwu** [comment]
Nah, tego nie mam

**Comment by TehFridge** [comment]
No to poprostu pobierz najnowszego hb-launchera z githuba i wypakuj na rootie karty. i gotowe. powinno zadziałać.

**Comment by radeczekuwu** [comment]
Dobra, po tym update ręcznym hb-launchera wszystko działa. Dzięki bardzo!
