### ISSUE TITLE
Błąd podczas uruchamiania

### ISSUE THREAD

**Issue by unicornsandcandies** [TehFridge/Zappka3DS#3]
![20241223_013813](https://github.com/user-attachments/assets/836f881e-57ae-4fd1-93f8-bb599263970c)

**Comment by TehFridge** [comment]
Jakie masz kupony na koncie (jeśli masz.)
Możliwe że jakiś konkretny powoduje błąd w apce.

**Comment by TehFridge** [comment]
Nvm namierzyłem problem.

**Comment by TehFridge** [comment]
https://github.com/TehFridge/Zappka3DS/releases/tag/v1.2.2

**Comment by unicornsandcandies** [comment]
Hej, dziękuję za szybką naprawę ale ta wersja aplikacji daje mi czarny ekran i nic się nie ładuje. Czy mogę mimo to w jakiś sposób załączyć logi lub pomóc naprawić?

**Comment by TehFridge** [comment]
okej tutaj mój błąd, zapomniałem jeden plik związany z debugowaniem usunąć 😭 
już naprawiam

**Comment by TehFridge** [comment]
pobierz z tego samego linku co dałem .3dsxa, podmieniłem na naprawionego

**Comment by unicornsandcandies** [comment]
> pobierz z tego samego linku co dałem .3dsxa, podmieniłem na naprawionego

Oki, dziękuję mocno :3
